FROM azul/zulu-openjdk:20-latest as build
WORKDIR /tmp
COPY daemon/ daemon/
COPY ./.git .git/
RUN cd daemon && ./gradlew bootJar

FROM azul/zulu-openjdk:20-latest as run
WORKDIR /app
COPY --from=build /tmp/daemon/build/libs/daemon.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
