import { contextBridge } from 'electron';
import { utilsBridge } from '../infra/rendererUtils/renderer';
import { subscriptionsBridge } from '../infra/subscriptions/renderer';
import { uiServiceBridge } from '../infra/ui/renderer';
import { daemonAddressSupplier, daemonHealthySupplier, daemonWsAddressSupplier } from '../infra/daemon/renderer';
import { configurationStore } from '../infra/store/store';
import { configurationStoreBridge } from '../infra/store/renderer';
import { appUpdaterBridge } from '../infra/autoupdate/renderer';

contextBridge.exposeInMainWorld('utils', utilsBridge);
contextBridge.exposeInMainWorld('subscriptions', subscriptionsBridge);
contextBridge.exposeInMainWorld('ui', uiServiceBridge);
contextBridge.exposeInMainWorld('isElectron', true);
contextBridge.exposeInMainWorld('daemonAddress', daemonAddressSupplier());
contextBridge.exposeInMainWorld('daemonWsAddress', daemonWsAddressSupplier());
contextBridge.exposeInMainWorld('daemonHealthy', daemonHealthySupplier);
contextBridge.exposeInMainWorld('NODE_ENV', process.env.NODE_ENV);
contextBridge.exposeInMainWorld('appVersion', process.env.npm_package_version);
contextBridge.exposeInMainWorld('configurationStore', configurationStoreBridge);
contextBridge.exposeInMainWorld('appUpdater', appUpdaterBridge);
